name: Setup Tools

description: Installs and configures the required .NET and MAUI tooling

runs:
  using: composite
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          10.0.x

    - name: Show .NET info
      shell: pwsh
      run: dotnet --info

    - name: Install .NET MAUI
      shell: pwsh
      run: dotnet workload install maui --source https://api.nuget.org/v3/index.json

    - name: Install Mac Catalyst workloads
      if: runner.os == 'macOS'
      shell: pwsh
      run: dotnet workload install maccatalyst maui-maccatalyst --source https://api.nuget.org/v3/index.json
